version: "3"
services:
  frontend:
    environment:
      - NODE_ENV=development
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v0.26.1
    volumes:
      - meilisearch-data:/data.ms

  data-fetcher:
    command: /bin/sh --verbose -c 'yarn install && yarn go'
    depends_on:
      - meilisearch

volumes:
  meilisearch-data: null
