version: "3"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
      - frontend-next:/app/.next
    command: /bin/sh --verbose -c 'yarn install && yarn dev'
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:v0.26.1
    ports:
      - 7700:7700
    volumes:
      - meilisearch-data:/data.ms

  data-fetcher:
    build:
      context: data-fetcher
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./data-fetcher:/app
      - data-fetcher-node_modules:/app/node_modules
    depends_on:
      - meilisearch
    command: /bin/sh --verbose -c 'yarn install && yarn go'

volumes:
  meilisearch-data: null
  frontend-node_modules: null
  frontend-next: null
  data-fetcher-node_modules: null
